public final class kotlinx.coroutines.CoroutineExceptionHandlerKt extends java.lang.Object
{

    public static final kotlinx.coroutines.CoroutineExceptionHandler CoroutineExceptionHandler(kotlin.jvm.functions.Function2)
    {
        kotlin.jvm.functions.Function2 $r0;
        kotlinx.coroutines.CoroutineExceptionHandler$Key $r1;
        kotlinx.coroutines.CoroutineExceptionHandlerKt$CoroutineExceptionHandler$1 $r2;
        kotlinx.coroutines.CoroutineExceptionHandler $r3;

        $r0 := @parameter0: kotlin.jvm.functions.Function2;

        $r1 = <kotlinx.coroutines.CoroutineExceptionHandler: kotlinx.coroutines.CoroutineExceptionHandler$Key Key>;

        $r2 = new kotlinx.coroutines.CoroutineExceptionHandlerKt$CoroutineExceptionHandler$1;

        specialinvoke $r2.<kotlinx.coroutines.CoroutineExceptionHandlerKt$CoroutineExceptionHandler$1: void <init>(kotlin.jvm.functions.Function2,kotlinx.coroutines.CoroutineExceptionHandler$Key)>($r0, $r1);

        $r3 = (kotlinx.coroutines.CoroutineExceptionHandler) $r2;

        return $r3;
    }

    public static final void handleCoroutineException(kotlin.coroutines.CoroutineContext, java.lang.Throwable)
    {
        kotlin.coroutines.CoroutineContext $r0;
        java.lang.Throwable $r1, $r6;
        kotlinx.coroutines.CoroutineExceptionHandler$Key $r2;
        kotlin.coroutines.CoroutineContext$Key $r3;
        kotlin.coroutines.CoroutineContext$Element $r4;
        kotlinx.coroutines.CoroutineExceptionHandler $r5;

        $r0 := @parameter0: kotlin.coroutines.CoroutineContext;

        $r1 := @parameter1: java.lang.Throwable;

     label1:
        $r2 = <kotlinx.coroutines.CoroutineExceptionHandler: kotlinx.coroutines.CoroutineExceptionHandler$Key Key>;

        $r3 = (kotlin.coroutines.CoroutineContext$Key) $r2;

        $r4 = interfaceinvoke $r0.<kotlin.coroutines.CoroutineContext: kotlin.coroutines.CoroutineContext$Element get(kotlin.coroutines.CoroutineContext$Key)>($r3);

        $r5 = (kotlinx.coroutines.CoroutineExceptionHandler) $r4;

     label2:
        if $r5 != null goto label3;

        staticinvoke <kotlinx.coroutines.CoroutineExceptionHandlerImplKt: void handleCoroutineExceptionImpl(kotlin.coroutines.CoroutineContext,java.lang.Throwable)>($r0, $r1);

        return;

     label3:
        interfaceinvoke $r5.<kotlinx.coroutines.CoroutineExceptionHandler: void handleException(kotlin.coroutines.CoroutineContext,java.lang.Throwable)>($r0, $r1);

     label4:
        return;

     label5:
        $r6 := @caughtexception;

        $r1 = staticinvoke <kotlinx.coroutines.CoroutineExceptionHandlerKt: java.lang.Throwable handlerException(java.lang.Throwable,java.lang.Throwable)>($r1, $r6);

        staticinvoke <kotlinx.coroutines.CoroutineExceptionHandlerImplKt: void handleCoroutineExceptionImpl(kotlin.coroutines.CoroutineContext,java.lang.Throwable)>($r0, $r1);

        return;

        catch java.lang.Throwable from label1 to label2 with label5;
        catch java.lang.Throwable from label3 to label4 with label5;
    }

    public static final java.lang.Throwable handlerException(java.lang.Throwable, java.lang.Throwable)
    {
        java.lang.Throwable $r0, $r1;
        java.lang.RuntimeException $r2;

        $r0 := @parameter0: java.lang.Throwable;

        $r1 := @parameter1: java.lang.Throwable;

        if $r0 != $r1 goto label1;

        return $r0;

     label1:
        $r2 = new java.lang.RuntimeException;

        specialinvoke $r2.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("Exception while trying to handle coroutine exception", $r1);

        $r1 = (java.lang.Throwable) $r2;

        staticinvoke <kotlin.ExceptionsKt: void addSuppressed(java.lang.Throwable,java.lang.Throwable)>($r1, $r0);

        return $r1;
    }
}
