public final class kotlinx.coroutines.flow.internal.ChildCancelledException extends java.util.concurrent.CancellationException
{

    public void <init>()
    {
        kotlinx.coroutines.flow.internal.ChildCancelledException r0;

        r0 := @this: kotlinx.coroutines.flow.internal.ChildCancelledException;

        specialinvoke r0.<java.util.concurrent.CancellationException: void <init>(java.lang.String)>("Child of the scoped flow was cancelled");

        return;
    }

    public java.lang.Throwable fillInStackTrace()
    {
        kotlinx.coroutines.flow.internal.ChildCancelledException r0;
        boolean $z0;
        java.lang.Throwable $r1;
        java.lang.StackTraceElement[] $r2;
        java.lang.Object[] $r3;

        r0 := @this: kotlinx.coroutines.flow.internal.ChildCancelledException;

        $z0 = staticinvoke <kotlinx.coroutines.DebugKt: boolean getDEBUG()>();

        if $z0 == 0 goto label1;

        $r1 = specialinvoke r0.<java.util.concurrent.CancellationException: java.lang.Throwable fillInStackTrace()>();

        return $r1;

     label1:
        $r2 = newarray (java.lang.StackTraceElement)[0];

        $r3 = (java.lang.Object[]) $r2;

        $r2 = (java.lang.StackTraceElement[]) $r3;

        virtualinvoke r0.<kotlinx.coroutines.flow.internal.ChildCancelledException: void setStackTrace(java.lang.StackTraceElement[])>($r2);

        $r1 = (java.lang.Throwable) r0;

        return $r1;
    }
}
